name: drinks_menue
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  flutter_svg: ^2.2.1
  flutter_native_splash: ^2.4.6
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.4"
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/other/icon.png"





flutter:

 
  uses-material-design: true

 
  assets:
    - assets/img/
    - assets/other/
    


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic


